### ISSUE TITLE
Arabic ULMFit link is not working

### ISSUE THREAD

**Issue by Yugioh1984** [Rashwan/Machine-Learning-Experiments#1]
Hello @Rashwan,
Thank you for sharing this very interesting work for the community. Especially that most of the work is focused on English and we found very few works on other languages.
I tried to download the Arabic ULMFit to test it and It seems that the link is not working.
Could you please check it?

**Comment by Rashwan** [comment]
Sorry for the wrong link. Updated Readme.md file
